---
noidd_root: ""
leveldb: ""
leveldb_recreate: false
logfile: ""
loglevel: "debug"
watch:
    #  - name: "watch_my_resolv_configs"
    # type: "filelist"
    #files:
    #  - "/etc/resolv.conf"
    # - "/lib/systemd/resolv.conf"
  - name: "watch_pam"
    type: "dir"
    root_dir: "/etc/pam.d"
#- name: "watch_etc_configs"
#   type: "glob"
#   root_dir: "/etc"
#   glob: "*/*.conf"
notifiers:
 - type: "twilio"
   twilio_api_key: 'AC19106ec2e6b25f81dcfda4c38a540da8'
   twilio_auth_sid_token: '19e837f2fb394c199dcdd1855dc85938'
   twilio_from_number: '+19294162087'
   recipients:
     - "+15512331518"
   batch: true
 - type: "stdout"
   batch: true

